package com.patient;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
public class Build {
    @Autowired
    JdbcTemplate jdbcTemplate = new JdbcTemplate();
    public List<Map<String,Object>> Build_sql(){
        List<Map<String,Object>> list = new ArrayList<>();
        Map<String,Object> map = new HashMap<>();


        map.put("id","2020016");
        map.put("name","陈韵岱");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E9%99%88%E9%9F%B5%E5%B2%B1.jpg");
        map.put("sex","女");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师、教授、研究员（知名专家）");
        map.put("tel","1731721xxxx");
        map.put("detail","医学博士、博士后、博士研究生导师。现任解放军总医院心内科主任、解放军老年心血管病研究所所长。北京市冠心病重点学科主要专家之一、全军心血管内科专业委员主任委员、中华医学会心血管病分会常委委员、秘书长、女性学组组长；亚太心脏联盟委员女性心脏委员会主席、中国医师协会心血管分会常委、北京医师协会心血管内科专科医师分会副会长、。中国国家863科技课题及国家自然基金评审专家。Journal of Geriatric Cardiology（SCI收录）主编、《中华老年多器官疾病杂志》副主编、《中国心脏介入杂志》副主编、《中国循证心血管医学杂志》副主编、《中华心血管病杂志》、《中国循环杂志》等杂志的编委。荣获军队医疗成果一等奖1项、教育部技术推广一等奖1项、军队医疗成果二等奖1项。牵头国家及省部级以上课题7项，在研科研经费2千余万元。以第一或通讯作者发表SCI 69篇，单篇IF 7.4，总IF 168.392，主编专著6部。培养博士后6名、博士22名、硕士16名。近5年诊治复杂冠心病患者3000余名，手术成功率达99%。主办两个国际知名会议、个人演示授课240余次，共培养各地医院骨干人才121名专家。相关技术在全国150余家医院广泛推广和应用。 从事冠心病介入治疗18年，对复杂冠心病介入治疗和冠脉腔内影像技术有较深造诣。应用国际先进的影像学技术并结合临床流行病学方法，不断探索和创新冠心病诊断治疗新技术，提高冠心病的个体化诊治水平；解决了冠心病介入治疗严重并发症的预警和防治难题。开拓性的开展国产药物洗脱支架的研发并进行新器械的临床评价和应用推广，取得了显著的社会和经济效益。研究得到国内外学术界的认可，有力推动了我国冠心病治疗水平的提高。在国内率先开展曾为'介入禁区'的无保护左主干病变介入治疗和切割球囊治疗支架再狭窄技术；创新性应用光学相干断层成像和CT新技术，优化冠脉介入治疗策略，显著提高复杂冠脉手术即刻成功率；建立介入术后无复流、造影剂肾病的防治新策略，改善远期疗效，居国际领先；是多个国产药物洗脱支架自主研发专利人和临床评价负责人。率先完成全军首例经皮主动脉瓣膜置入术、顽固性高血压的肾动脉交感神经Simplicity射频消融术。");
        map.put("e_mail","1832315xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020017");
        map.put("name","王思让");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E7%8E%8B%E6%80%9D%E8%AE%A9.jpg");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师");
        map.put("tel","1832415xxxx");
        map.put("detail","对心血管内科疾病有丰富的诊治经验。对心电图的临床应用及心律失常的诊治有较深造诣。参与编著《中国大百科全书.心脏病学卷》、《临床心电图学》（第三、四、五版）。主编《临床心电图图谱》（第一、二版）、《临床心脏电生理与药理学-基础与临床》、《重症加强监护学》。共培养博士及硕士研究生13名。于国内外杂志发表论文60余篇。曾任《中华心血管病杂志》第三、第四届编委。《中国介入心脏病学杂志》第一届编委。现任中华医学会心电生理起搏学会心电图学组专业委员，《中华心律失常学杂志》常务编委。1992年起享受政府特殊津贴。 ");
        map.put("e_mail"," 1832315xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020018");
        map.put("name","王玉堂");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E7%8E%8B%E7%8E%89%E5%A0%82.jpg");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师");
        map.put("tel","1731721xxxx");
        map.put("detail","南楼心内科名誉主任、博士生导师。中国生物医学工程学会起搏与电生理分会青年委员、《中国实用内科杂志》、《临床心电学杂志》编委。 1992年开始并主持我院射频消融治疗快速心律失常及临床电生理检查工作。完成射频消融治疗快速性心律失常500余例次，成功率达96％，包括室上性心动过速、室性心动过速、房性心动过速、心房扑动等，达到国内先进水平。尤其值得一提的是正确诊断并成功消融治疗了国内首例Mahaim氏纤维并室上速患者，受到国内外专家的一致好评，打破了开展射频消融几年来中国人没有Mahaim氏预激的说法。主编《导管消融治疗学》（天津科技出版社，1996年）等专著，发表论文20余篇。");
        map.put("e_mail"," 1832315xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020019");
        map.put("name","张志寿");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E5%BC%A0%E5%BF%97%E5%AF%BF.jpg");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师");
        map.put("tel","18312941xxx");
        map.put("detail","长期从事心血管内科专业工作，历任住院医师、主治医师、科副主任、副主任医师、副教授、科主任、主任医师、教授、硕士研究生导师。曾任师干内科主任、师干内科心内科主任、心血管内科副主任、心血管内科（师干）主任。兼任中国医学会心血管病专业委员会主任委员、中国保健医学会心脏学会委员、中国医药信息学会心功能学会常务委员、中华医学会医学工程学会医学电阻抗学组副组长、《心脏杂志》编委、《人民军医》特约编审等。曾任博士研究生答辩评审委员等。 从医四十五年，在心血管内科的医疗、教学、科研等工作方面具有丰富的经验，造诣很深。多次受到嘉奖及评为先进个人。医德高尚、医术精湛、医风严谨，深受病人普遍赞誉。擅长于冠心病、高血压、心脏瓣膜病、心肌病、心律失常、心力衰竭、多器官功能衰竭等的诊断、治疗和抢救。在抢救急性心肌梗死、急性心力衰竭、严重心律失常、不稳定型心绞痛、难治性心力衰竭、多器官功能衰竭等方面达国内外先进水平。研究方向是冠心病的临床及实验研究。已培养硕士研究生5名、进修生近300名。发表论文近百篇，主编专著6部（如《心肌病的诊断与治疗》、《医生的思维与工作技巧》、《冠心病专家门诊150问》等）。参编专著6部（如《心血管内科疾病进展》、《现代医院卫生学》、《名医手记》等）。审阅专著1部（《临床心电图快速阅读》）。是有突出贡献的专家，1993年起享受国务院政府特殊津贴。我国著名心血管病专家。本人简介被收入《北京名医》、《中国当代医药界名人录》、《世界优秀专家人才名典》。");
        map.put("e_mail"," 1835132xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020020");
        map.put("name","赵玉生");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E8%B5%B5%E7%8E%89%E7%94%9F.jpg");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师");
        map.put("tel","1831924xxxx");
        map.put("detail"," 老年心血管病专家、博士生导师、副所长。1979年毕业于第一军医大学、军医进修学院老年医学硕士。作为主要负责人承担过军队'九五'、'十五'、'十一五'重点或专项科研基金课题多项、国家863课题1项、国家自然科学基金课题1项、，国家科技部合作课题2项、国际合作课题2项。现承担国家卫生行业专项和国家科技支撑计划合作课题各1项及国际合作课题2项。获北京市科学技术一等奖1项、军队科技进步二等奖1项、军队医疗成果一等奖2项、二等奖3项、三等奖1项、解放军总医院科技成果奖2项。1996年被评为解放军总医院十佳医生。现任中国医师协会心血管内科医师分会委员、中国医药教育协会常务理事、全军医学科学技术委员会委员、全军老年医学专业委员会主任委员，解放军医学杂志、实用老年医学、中华老年多器官疾病杂志、国际老年医学杂志、中华实用医学杂志等编委、常务编委及副主编。荣立过三等功、多次被评为优秀党员、优秀基层干部，获得过牟善初医疗保健基金奖，总医院突出贡献奖，军队优秀科技干部二类特殊津贴等奖励。长期从事老年冠心病的临床防治及基础研究，潜心研究心肌梗死、心力衰竭和心律失常的机制和救治。对老年急性冠脉综合征、心力衰竭、心律失常、多器官功能不全综合征、难治性高血压病和心血管病非心脏手术围手术期处理等老年危重症有丰富的临床救治经验。在国内最早开展了干免疫方法测定心肌肌钙蛋白I， N-端脑钠肽前体评价心功能、大动脉弹性测定等研究，促进了这些新技术在我国的应用。2000年以来，所收治的急性心肌梗死的抢救成功率达96%以上，合并心源性休克的抢救成功率达92.3%，先后使许多合并6个以上脏器衰竭濒临死亡的极危重患者救治成功，获得患者及其家属的高度赞誉。 ");
        map.put("e_mail"," 1832512xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020001");
        map.put("name","许峰");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E8%AE%B8%E5%B3%B0.png");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","心血管内科");
        map.put("position","主任医师");
        map.put("tel","1731721xxxx");
        map.put("detail"," 许锋，心血管内科主任医师。于1982年12毕业于广州中山医科大学医疗系，分配至北京医院。曾于1985年在中国人民解放军301医院儿科进修心导管，之后赴美国加州罗玛琳达大学医学中心进修冠状动脉造影PTCA术一年，后又于1998赴新加坡国家心脏中心进修冠心病介入诊断及治疗一年。具有丰富的临床工作经验，能够独立处理各种心脏急重症及复杂病例。主要业务专长为冠心病及外周血管介入治疗（如冠状动脉支架及外周血管支架治 疗等），心脏危重症的抢救，如急性心肌梗死、心力衰竭、心源性休克、严重心律失常和高血压、高脂血症、冠心病的防治、老年人心脏保健等。曾参加编写'实用老年医学小百科' 、《糖尿病实用诊疗手册》、《心脏急症》、《新编心血管疾病鉴别诊断学》等医学专著，发表医学论文10余篇。先后主持'脂蛋白(a)的生理变异和其应激变化'和'冠脉钙化与冠心病之关系'两项院级科研课题。");
        map.put("e_mail"," 1731721xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020002");
        map.put("name","肖钢");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E8%82%96%E5%88%9A.png");
        map.put("sex","男");
        map.put("authority",true);
        map.put("department","普通外科");
        map.put("position","主任医师");
        map.put("tel","1310101xxxx");
        map.put("detail"," 肖刚，主任医师 北京医院普通外科主任，胃肠外科主任，北京大学医学部硕士研究生导师1985年毕业于白求恩医科大学，从事普外科临床工作30余年，1995年以来多次赴日本研修微创外科腹腔镜手术、胃肠道肿瘤的外科手术及综合治疗。在消化道疾病及胃肠道肿瘤的治疗、腹腔镜手术、甲状腺疾病、外科营养支持治疗、围手术期处理及其他外科疾病诊治方面均有较丰富的临床经验。参加编现代主治医生提高丛书系列《基本外科主治医生580问》以及《中华普通外科临床手册》、《中老年人常见疾病》等，在国内外医学期刊上发表论文50余篇。");
        map.put("e_mail"," 1331211xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020003");
        map.put("name","于会艳");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E4%BA%8E%E4%BC%9A%E8%89%B3.png");
        map.put("sex","女");
        map.put("authority",false);
        map.put("department","神经内科");
        map.put("position","副主任医师");
        map.put("tel","1330101xxxx");
        map.put("detail"," 于会艳，医学博士，神经内科副主任医师。中华医学会神经病学分会神经电生理学组委员，北京神经内科学会神经变性疾病委员会委员，中国医促会中老年医疗保健分会委员，中国医促会神经退行性变学组，中国微循环学会变性病分会阿尔茨海默病生物标志物学组委员。2000年本科毕业于山东大学医学院，2004年获得山东大学医学院神经病学硕士学位，同年分配至北京医院神经内科工作，2006年晋升为主治医师，2011年晋升副主任医师。2017至2018年在美国芝加哥大学医学中心的认知障碍诊疗中心、帕金森病和运动障碍性疾病中心做访问学者。2020年获得北京大学医学部神经病学博士学位。长期从事神经内科临床工作并承担北京大学医学部教学工作。目前主要研究方向为老年神经系统变性疾病，周围神经病、运动神经元病、癫痫。曾参与多项国家、省部级课题，在国内外期刊发表文章20余篇。");
        map.put("e_mail","1331212xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020004");
        map.put("name","裕东洁");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E8%A3%95%E4%B8%9C%E6%B4%81.png");
        map.put("sex","女");
        map.put("authority",true);
        map.put("department","肾脏内科");
        map.put("position","主任医师");
        map.put("tel","1630101xxxx");
        map.put("detail"," 裕东洁，主任医师。1968年毕业于首都医科大学 从事内科、肾脏内科、老年病的临床诊治工作。专长肾脏疾病、老年病的诊治。");
        map.put("e_mail"," 13342211xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020005");
        map.put("name","缪刚");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E7%BC%AA%E5%88%9A.png");
        map.put("sex","男");
        map.put("authority",false);
        map.put("department","普通外科");
        map.put("position","主任医师");
        map.put("tel","1332101xxxx");
        map.put("detail","1995年毕业于复旦大学医学院（原上海医科大学），后在日本大阪大学外科学习并取得医学博士学历和学位。曾经在美国加州大学旧金山分校医学院工作与学习，参与并发表多篇中英文医学论文，其中第一作者论文(和通讯作者15篇。其中SCI论文11篇，核心期刊4篇。参与并完成甲状腺和甲状旁腺手术超过千例。");
        map.put("e_mail"," 13342101xxx@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020011");
        map.put("name","杨长青");
        map.put("sex","男");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E6%9D%A8%E9%95%BF%E9%9D%92.png");
        map.put("authority",true);
        map.put("department","消化内科");
        map.put("position","主任医师");
        map.put("tel","17317267584");
        map.put("detail"," 杨长青，同济大学附属同济医院大内科主任、内科教研室主任、消化内科主任，消化内科教授、主任医师、博士生导师，首届'同济名医'；曾留学于美国哈佛大学医学院，现为上海市优秀学科带头人，上海市消化疾病质控专家，美国胃肠病协会(AGA)会员，美国肝病研究协会(AASLD)会员，中国老年医学会消化分会副会长，中国医促会消化分会常委兼内镜学组委员，中国医师协会消化分会委员，中国研究型医院学会门脉高压学组副组长，中华医学会消化分会肝胆协作组委员和疑难重症协作组委员，中华医学会肝病分会药物性学组委员兼秘书，上海中西医结合学会消化分会副主委兼肝病学组组长，上海医学会肝病分会副主委兼药物性肝病学组组长，上海医学会消化分会常委兼秘书。至2018年已发表论文230余篇，其中SCI论文100余篇，主持了包括国家自然科学基金重点项目、面上项目等多项国家和部省级研究课题，获省级科技进步二等奖1项、三等奖4项。 临床以复杂疑难的肝胆疾病、胃肠疾病诊治为擅长，特别在肝硬化门脉高压及其并发症（如食道胃底静脉曲张，难治性腹水）的诊治、消化疾病的内镜诊疗等方面有特色。");
        map.put("e_mail"," 17317267584@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        map.put("id","2020012");
        map.put("name","陈燕");
        map.put("pic","https://soa-project.oss-cn-shanghai.aliyuncs.com/%E5%8C%BB%E7%94%9F%E5%9B%BE%E7%89%87/%E9%99%88%E7%87%95.png");
        map.put("sex","女");
        map.put("authority",false);
        map.put("department","神经内科");
        map.put("position","副主任医师");
        map.put("tel","13101007350");
        map.put("detail"," 陈燕，从医近三十年，一直从事神经内科临床及神经电生理诊断工作，善于将两者有效结合，为麻木无力、肌肉萎缩、肌肉跳动的患者寻找诊断线索，擅长周围神经病、神经肌肉接头病的电诊断，对周围神经病、神经肌肉接头病、肌肉疾病的诊断积累了较多经验，担任上海脑电临床神经电生理专业委员会委员及神经肌肉病与电生理学组委员，发表专业论文数篇。");
        map.put("e_mail"," 13101007350@163.com");
        map.put("password","123456");
        list.add(map);
        map = new HashMap<>();
        return list;
    }
    @GetMapping("/hellooo")
    public boolean hello(){
        List<Map<String,Object>> list = Build_sql();
        list.forEach((result)->addd(result));
        return true;
    }

    public void addd(Map<String,Object> map){
        String id = (String)map.get("id");
        String name = (String)map.get("name");
        String pic = (String)map.get("pic");
        String sex = (String)map.get("sex");
        boolean authority = (boolean)map.get("authority");
        System.out.println(authority);
        String department = (String)map.get("department");
        String position = (String)map.get("position");
        String detail = (String)map.get("detail");
        jdbcTemplate.update("insert into doctor values(?,?,?,?,?,?,?)",id,sex,name,position,department,detail,pic);
    }
}
